<?php

function mysearch_permission() {
  return array(
    'access simple page' => array(
      'title' => t('Access simple page'),
      'description' => t('Allow users to access simple page'),
    ),
    'access arguments page' => array(
      'title' => t('Access page with arguments'),
      'description' => t('Allow users to access page with arguments'),
    ),
  );
}
function mysearch_menu() {

  
  $items['mysearch/%'] = array(
    'page callback' => 'mysearch_arguments',
    'page arguments' => array(1),
    'access arguments' => array('access arguments page'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function mysearch_arguments($first) {
$search_for = array('@number' => $first);
	$search_for1 = $search_for['@number'];
  $allcontent = mysearch_myfunc($search_for1);

  $list[] = t("First number was @number.", array('@number' => $first));
  $list[] = t("List of nodes:".$allcontent);
 
 
  
  
  //$search_for1 = $search_for['@number'];
  //print $search_for1;
  
 print_r($search_for['@number']);

  $render_array['mysearch_arguments'] = array(
    
    '#theme' => 'item_list',
    
    '#items' => $list,
    '#title' => t('Argument Information'),
  );
  
  
  return $render_array;
}

function mysearch_myfunc($urlarg){
//print"<pre>";
$url = $_SERVER['SERVER_NAME'];
//$str = $_SERVER['SCRIPT_URL'];
//print"<pre>";

//$token = substr($str,10);
//print $token; /// example word from url 

$query = "SELECT entity_id FROM `field_data_body` WHERE body_value LIKE '%$urlarg%'";
$search_results = db_query($query);
$allcontent = "";

 foreach($search_results as $record){
 
$nid = $record->entity_id;
//$node = node_load(array('nid' => $nid));
$nodes1 = node_load_multiple($nids = array('nid' => $nid));
//print"<pre>";
 
 //print_r($nodes1[$nid]->title);
 
//print"<pre>";
$path=drupal_get_path_alias('node/'.$record->entity_id);
$link = "<a href=\"/".$path."\">See node</a>"; 

//print $link; // !!!!
	
//print"<pre>";	  
// print_r($node->title); //!!!!
 
  $allcontent = $allcontent."<br />"."<h2>".$nodes1[$nid]->title."</h2>"."<br />".$link."<br />";

//print"<pre>";	
/*
print"<pre>";	  
 print_r($node);
print"<pre>";
*/
    
  }
  
  
return $allcontent;


}
